spring.application.name=InstitutoMayor
spring.datasource.url=jdbc:mysql://localhost:3306/instituto_mayor
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true